### ISSUE TITLE
Fix GUI horizontal spacing of hexagons (Optional)

### ISSUE THREAD

**Issue by mjlewis-millersville** [mucsci-students/2023sp-420-Maryjane#151]
``
Optional!!!

Fix GUI horizontal spacing of hexagons

- [ ] Fix GUI horizontal spacing of hexagons

Primary: @jjriver1

Secondary: @mharrison7787

Size: Iron

Actual Size: (e.g. t-shirt size after completion)

Actual Time: (in minutes or hours -- after completion)
``

**Comment by JSteve0** [comment]
This is optional!
