### ISSUE TITLE
GUI: Dark mode should have lower contrast. 

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2023sp-420-Maryjane#180]
The bright colors are too much for my nocturnal eyes. If it's dark mode, it must be dark mode for all rendered components. This should work even if the host OS is in light mode.

``
GUI: Dark Mode

- [ ] Do the above

Primary: @OhMyDayz2023 

Secondary: @jjriver1 

Size: lapis

Actual Size: (e.g. t-shirt size after completion)

Actual Time: (in minutes or hours -- after completion)
``

**Comment by JSteve0** [comment]
Completed by removing dark mode.
