### ISSUE TITLE
Project does not build on linux due to case-sensitive npm module requirement

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2023sp-420-Maryjane#252]
<img width="672" alt="Screenshot 2023-04-25 at 6 54 43 PM" src="https://user-images.githubusercontent.com/2007799/234441457-a9631672-4c18-4d9c-ae38-9ddbfe074274.png">

I had to do the following to make this work

**Comment by mharrison7787** [comment]
Fixed this by changing Vorpal setup
