### ISSUE TITLE
Show-Found-Words Method

### ISSUE THREAD

**Issue by jjriver1** [mucsci-students/2023sp-420-Maryjane#71]
- [x] Create static method
- [x] Check Edge cases
- [x] Collect the array of words from GameManager class
- [x] Use random generator to shuffle the puzzle
- [x] Tested through terminal on multiple puzzles

- Primary: @OhMyDayz2023
- Secondary: @mharrison7787
- Size: Lapis
- Actual Size: Lapis
- Actual Time: 15 minutes

**Comment by OhMyDayz2023** [comment]
Finished Method.
